
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "worker"
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: <your-acr>.azurecr.io/worker:v1
